os:
  - linux
  - osx

sudo: required

dist: trusty

osx_image: xcode8.3

language: node_js

node_js:
  - 8

env:
  - export NODE_VERSION="8"

cache:
  yarn: true
  directories:
    - node_modules
    - app/node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - icnsutils
      - graphicsmagick
      - xz-utils
      - gcc-multilib
      - g++-multilib
      - rpm
      - libavahi-compat-libdnssd-dev

before_install:
  - npm config set python `which python`

install:
  - export CXX="g++-4.8"
  - yarn
  - cd app && yarn && cd ..

before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16";
      export DISPLAY=':99.0';
      Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & echo "nothing";
      sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils xorriso;
    fi

script:
  # - npm run lint
  # - npm run test
  - npm run package-ci
  - npm run test-e2e
